service: orangedao-gem-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 256
  architecture: arm64

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

package:
  include:
    - views/**
